data([what, in, the, name, of]).
data([how, is, that, one]).
data([how]).
data([who]).
data([hi]).
data([cat]).
data([what, in]).
data([media]).
data([question]).
data([dog]).
data([from,stranger]).
data([bird]).
data([alligator]).
data([gator]).
data([cheesepuff]).
data([umbrella]).
data([torrent]).
data([juggling]).
data([big]).
data([ball]).
data([balloon]).
data([ballooga,whale]).
data([hello]).
data([saying,to,me]).
data([my]).
data([johnson]).
data([brazzen]).
data([brass]).
data([tax,derby]).
data([exit]).
data([animal,and,cheese]).
data([banana]).
data([okay]).
data([well]).
data([so]).
data([ca]).
data([sso]).
data([hahaha]).
data([laugh]).
data([if]).
data([then]).
data([angel]).
data([say]).
data([vanglorious,on,high]).
data([low]).
data([or]).
data([sonalities,hence,builds,upon,their]).
data([b]).
data([c]).
data([d]).
data([a]).
data([tok]).
data([bok]).
data([mok]).
data([mock]).
data([bog]).
data([bump]).
data([works]).
data([words]).
data([word]).
data([work]).
data([tor]).
data([downpour]).
data([harken,back,you]).
data([sing]).
data([why]).
data([night,tonight]).
data([dance]).
data([wonderful]).
data([stay]).
data([sat]).
data([demon]).
