data([chase]).
data([palace,hills]).
data([cheese,cat]).
data([chess,in,the,guinea,pig]).
data([super,duper]).
data([artichoke]).
data([okey,dokey]).
data([water,boiler]).
data([joyful,paradigms,of,greater,truth]).
data([doeful,inquiry]).
data([are,you,a,friend]).
data([with,enemies,like,these,who,needs]).
data([eating,cereal]).
data([trader,joes,and,trader,marvins]).
data([list,indices,must,be,integers,not,tuple]).
data([accessing,data,throws,an,error,occasionally]).
data([give,me,problems]).
data([always,working]).
data([honking,for,no,reason]).
data([resulting,is,weirder,sentences]).
data([okay,here,goes,eliza]).
data([this,free,spirit,more,than,just,friends]).
data([we,have,work,to,do]).
data([question,mark]).
data([dont,ask,dont,tell]).
data([takes,exactly,one,argument]).
data([how,fast]).
data([what]).
data([raises]).
data([know]).
data([still,executed,synchronously,huh]).
data([boris]).
data([feverishly,changing]).
data([banana]).
data([chesblue]).
data([moon]).
