data([what, in, the, name, of]).
data([how, is, that, one]).
data([how]).
data([who]).
data([hi]).
data([cat]).
data([what, in]).
data([media]).
data([question]).
data([dog]).
data([from,stranger]).
data([bird]).
data([alligator]).
data([gator]).
data([cheesepuff]).
data([umbrella]).
data([torrent]).
data([juggling]).
data([big]).
data([ball]).
data([balloon]).
data([ballooga,whale]).
data([hello]).
data([saying,to,me]).
data([my]).
data([johnson]).
data([brazzen]).
data([brass]).
data([tax,derby]).
data([exit]).
data([animal,and,cheese]).
data([banana]).
data([okay]).
data([well]).
data([so]).
data([ca]).
data([sso]).
data([hahaha]).
data([laugh]).
data([if]).
data([then]).
data([angel]).
data([say]).
data([vanglorious,on,high]).
data([low]).
data([or]).
data([sonalities,hence,builds,upon,their]).
data([b]).
data([c]).
data([d]).
data([a]).
data([tok]).
data([bok]).
data([mok]).
data([mock]).
data([bog]).
data([bump]).
data([works]).
data([words]).
data([word]).
data([work]).
data([tor]).
data([downpour]).
data([harken,back,you]).
data([sing]).
data([why]).
data([night,tonight]).
data([dance]).
data([wonderful]).
data([stay]).
data([sat]).
data([demon]).
data([hat]).
data([some]).
data([org]).
data([full]).
data([flower]).
data([flowing]).
data([remembrance]).
data([past]).
data([cannot]).
data([output]).
data([str]).
data([object]).
data([objects]).
data([whay]).
data([hedgehog]).
data([fog]).
data([log]).
data([tog]).
data([toggle]).
data([struggle]).
data([born]).
data([more,could,not,be,said,for]).
data([science]).
data([takes]).
data([cats]).
data([increase]).
data([manifold]).
data([desire]).
data([pay,fair]).
data([animalian,gesture]).
data([cauliflower]).
data([mayflower]).
data([do,your,thing]).
data([have]).
data([know]).
data([stein]).
data([choosing]).
data([same]).
data([some]).
data([sword]).
data([so]).
data([okay]).
data([fill]).
data([the,gap]).
data([into]).
data([a,new,paradise]).
data([sol]).
data([same]).
data([intelligence]).
data([sword]).
data([strike]).
data([cat]).
data([failproof]).
data([failsafe]).
data([vouchsafe]).
data([fall]).
data([mat]).
data([too,much]).
data([fiddle]).
data([window]).
data([world]).
data([explanation]).
data([explanatory]).
data([summer]).
data([summertime]).
data([solace]).
data([setting]).
data([instruments]).
data([bubble]).
data([double]).
data([sail]).
data([tail]).
data([wings]).
data([soot]).
data([teal]).
data([trailing]).
data([before,this]).
data([magical]).
data([sym]).
data([all]).
data([tomato,pool]).
data([real]).
data([value]).
data([seal]).
data([away,an,eternal]).
data([explain]).
data([three]).
data([four]).
data([door]).
data([peace]).
data([mother,flippin]).
data([earth]).
data([answering]).
data([tarrying]).
data([floor]).
data([coconut]).
data([sweet]).
data([flavor]).
